baseURL = "https://www.chapliboy.com/"
languageCode = "en-us"
title = "chapliboy"
theme = "notebook"

[params]
siteHeader = "chapliboy"
siteSubheader = "gamedev and things"
thumbnail = "https://www.chapliboy.com/thumbnail.png"
description = "making games that create joy by exploring simple systems and realizing emergent interactions"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
